apiVersion: v1
kind: Service
metadata:
  name: devops-capstone-green
  labels:
    app: devops-capstone-green
spec:
  type: LoadBalancer
  selector:
    app: devops-capstone-green
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
      protocol: TCP