apiVersion: v1
kind: Service
metadata:
  name: devops-capstone
  labels:
    app: devops-capstone-green
spec:
  type: LoadBalancer
  selector:
    app: devops-capstone-green  
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP