apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-capstone-blue
  labels:
    app: devops-capstone-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-capstone-blue
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: devops-capstone-blue
    spec:
      containers:
        - image: josielbr/devops-capstone-blue:latest
          imagePullPolicy: Always
          name: devops-capstone-blue
          ports:
            - containerPort: 30000           