apiVersion: v1
kind: Service
metadata:
  name: devops-capstone-blue
  labels:
    app: devops-capstone-blue
spec:
  type: LoadBalancer
  selector:
    app: devops-capstone-blue
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP